service: stori-challenge
plugins:
  - serverless-dotenv-plugin


frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  region: ${self:custom.config.region}
  environment:
    REGION: ${self:custom.config.region}
    

custom:
  stage: ${opt:stage, env:BRANCH, "main"} 
  bucket: ${self:custom.config.upload_bucket}
  config: ${file(data/lambda_config.json)}

package:
  exclude:
    - ./**
  include:
    - ./**

functions:
  upload-processor:
    handler: stori-challenge-lambda
    events:
      - s3: 
          bucket: ${self:custom.config.upload_bucket}
          event: s3:ObjectCreated:*
          existing: true